### ISSUE TITLE
"토탐정" 확장 프로그램의 정보 업데이트를 부탁드립니다!

### ISSUE THREAD

**Issue by wzrabbit** [RanolP/awesome-baekjoon#6]
안녕하세요, 저는 토탐정을 개발 및 유지보수하고 있는 요술토끼라고 합니다. 변경점을 아래에 적어두고자 하니, 해당 정보를 반영하여 업데이트를 부탁드려도 괜찮을까요?

## 지원 브라우저 🌏 
- Chrome → Chrome, **Whale**, **Firefox**

`v1.2` 를 기점으로 웨일 스토어, Firefox Add-ons에도 프로젝트를 배포했습니다. 아래는 링크입니다.
- **Whale**: https://store.whale.naver.com/detail/pkigleffcifanlafphnjkdpkfippibcm
- **Firefox**: https://addons.mozilla.org/ko/firefox/addon/%ED%86%A0%ED%83%90%EC%A0%95/

## 기능 🔧 

기존 기능에 더해, 아래의 기능을 제공함을 추가 명시해주셨으면 좋겠습니다. 랜덤 디펜스 또한 확장 프로그램의 핵심 기능이며, 이후 개발할 기능들도 랜덤 디펜스와 관련이 있습니다.

워딩은 원하시는대로 적어주셔도 돼요.

- 사용자가 편리하게 랜덤 디펜스를 이용할 수 있도록 보조하는 기능을 제공합니다.

구체적으로는 아래의 기능을 제공해요. (단순히 이해를 돕기 위함입니다)

- 백준에서 단축키 단 한 번으로, 빠르게 랜덤 디펜스를 시작할 수 있어요.
- 자주 사용하는 검색 쿼리를 저장할 수 있는 슬롯을 최대 10개까지 사용할 수 있으며, 슬롯 번호에 대응하는 숫자와 조합한 단축키를 사용해 원하는 쿼리로 랜덤 디펜스를 자유자재로 시작할 수 있어요.
- 솔브드의 검색 쿼리에 익숙하지 않더라도 쉽게 쿼리를 작성할 수 있어요.

![image](https://github.com/user-attachments/assets/a9694398-8ef8-41c7-ab68-7bd2eaeb6d1d)
![image](https://github.com/user-attachments/assets/9b5c23b7-2c1e-45f9-8e69-9131c764d8f2)

감사합니다 😊

**Comment by RanolP** [comment]
3a2f67593234523dad7cb21df2589b86eb6d9546 에서 반영했습니다. 추가 변경이 필요하다면 이슈 리오픈 후 수정을 요청해주세요.
